"""baseline

Revision ID: ad4c7047559a
Revises: 
Create Date: 2026-04-21 13:41:57.107431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('territory', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('wikidata_id', sa.String(length=16), nullable=True),
    sa.Column('wikipedia_title', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('preliminary', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('long_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tag',
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('wikidata_id', sa.String(length=16), nullable=True),
    sa.Column('wikipedia_title', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('is_seated', sa.Boolean(), nullable=True),
    sa.Column('is_mandated', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(length=256), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=True),
    sa.Column('wom', sa.Boolean(), nullable=True),
    sa.Column('party_repr', sa.String(length=256), nullable=False),
    sa.Column('party_name', sa.String(length=32), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['party_name'], ['party.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('party_name', sa.String(length=32), nullable=False),
    sa.Column('thesis_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['party_name'], ['party.name'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', 'thesis_id', name='u_quizanswer')
    )
    op.create_table('tags',
    sa.Column('tag_title', sa.String(length=128), nullable=False),
    sa.Column('thesis_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['tag_title'], ['tag.title'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('tag_title', 'thesis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('quiz_answer')
    op.drop_table('position')
    op.drop_table('thesis')
    op.drop_table('result')
    op.drop_table('tag')
    op.drop_table('party')
    op.drop_table('election')
    # ### end Alembic commands ###
